### ISSUE TITLE
Android Build Failure - bad class file magic (cafebabe) or version (0034.0000)

### ISSUE THREAD

**Issue by peterGraf** [artoolkit/artoolkit5#120]
I wanted to try out artoolkit5 on Android.

I have a Mac with the latest OS X El Captain,
I tried with Java versions 1.8.0_20, 1.8.0_91 and 1.8.0_92, all with the same
problem. 

When I Google the problem, I see some old answer posts claiming that I should use a Java 1.6 compiler, is that really the solution?

When I try to run the arSimple example I get the following error.

```
00:06:19 Executing tasks: [clean, :aRSimple:generateDebugSources, :aRSimple:compileDebugSources]
00:06:21 Gradle build finished in 2s 48ms
00:06:21 Gradle sync started
00:06:23 Gradle sync completed
00:09:35 Executing tasks: [:aRSimple:assembleDebug]
00:09:38 Gradle build finished with 21 error(s) in 2s 419ms

Information:Gradle tasks [:aRSimple:assembleDebug]
:aRSimple:preBuild UP-TO-DATE
:aRSimple:preDebugBuild UP-TO-DATE
:aRSimple:checkDebugManifest
:aRSimple:preReleaseBuild UP-TO-DATE
:aRSimple:prepareARSimpleProjARBaseLibUnspecifiedLibrary UP-TO-DATE
:aRSimple:prepareDebugDependencies
:aRSimple:compileDebugAidl UP-TO-DATE
:aRSimple:compileDebugRenderscript UP-TO-DATE
:aRSimple:generateDebugBuildConfig UP-TO-DATE
:aRSimple:generateDebugAssets UP-TO-DATE
:aRSimple:mergeDebugAssets UP-TO-DATE
:aRSimple:generateDebugResValues UP-TO-DATE
:aRSimple:generateDebugResources UP-TO-DATE
:aRSimple:mergeDebugResources UP-TO-DATE
:aRSimple:processDebugManifest UP-TO-DATE
:aRSimple:processDebugResources UP-TO-DATE
:aRSimple:generateDebugSources UP-TO-DATE
:aRSimple:processDebugJavaRes UP-TO-DATE
:aRSimple:compileDebugJavaWithJavac UP-TO-DATE
:aRSimple:compileDebugSources UP-TO-DATE
:aRSimple:preDexDebug
:aRSimple:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
Error:com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
	at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
	at com.android.dx.command.dexer.Main.processClass(Main.java:749)
	... 21 more

... the same error repeats 19 times ...

20 errors; aborting
Error:Execution failed for task ':aRSimple:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
Information:BUILD FAILED
Information:Total time: 1.93 secs
Information:21 errors
Information:0 warnings
Information:See complete output in console
```

**Comment by peterGraf** [comment]
I found the solution in the artoolkit pages

http://artoolkit.org/community/forums/viewtopic.php?f=26&t=9502

**Comment by BoiseBaked** [comment]
Instead of using the 1.8 Java compiler, use the 1.7 version. It difficult to find the 1.6 version of the JDK these days so it's hard to go back to it.

**Comment by peterGraf** [comment]
I switched to the 1.7 compiler by using these lines in the build.gradle of module aRSimple

```
tasks.withType(JavaCompile) {
  sourceCompatibility = JavaVersion.VERSION_1_7
  targetCompatibility = JavaVersion.VERSION_1_7
}
```

**Comment by peterGraf** [comment]
To solve the problem without editing the build.gradle for each and every project, I downloaded an JDK 1.7 and configured AS 2.1.1 to use it.

Under
AS / File / Project Structure 
select SDK Location and set the path to the JDK location:
e.g.:

`/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home`

**Comment by BoiseBaked** [comment]
tasks.withType(JavaCompile) {
  sourceCompatibility = JavaVersion.VERSION_1_7
  targetCompatibility = JavaVersion.VERSION_1_7
}

BTW, those lines in the module build.gradle file where once added for you by a File/Project Structure... setting. Seemingly, it was Android's intent to have the AS IDE preferences update the project and module gradle files so they didn't have to be edited directly. I can no longer find the setting in the 2.1.1 version of the AS IDE. It's difficult to keep the code base up-to-date to the constant IDE, SDK and NDK changes.
