### ISSUE TITLE
jni build fails

### ISSUE THREAD

**Issue by tzaccai** [artoolkit/artoolkit5#128]
hi,
i downloaded the project (zip file for windows, using android studio)
when i try to run the nftSampleProj from AS i get the following exception:

-------------------------------------

FATAL EXCEPTION: main
 Process: org.artoolkit.ar.samples.NftSimple, PID: 5100  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.artoolkit.ar.samples.NftSimple-2/base.apk"],nativeLibraryDirectories=[/data/app/org.artoolkit.ar.samples.NftSimple-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libc++_shared.so"
                                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                                      at java.lang.System.loadLibrary(System.java:1076)
                                                                                      at org.artoolkit.ar.samples.nftSimple.nftSimpleActivity.<clinit>(nftSimpleActivity.java:82)
                                                                                      at java.lang.Class.newInstance(Native Method)
                                                                                      at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-22 12:05:36.154 5100-5100/org.artoolkit.ar.samples.NftSimple I/Process: Sending signal. PID: 5100 SIG: 9

---------------------------------------

so i tried to compile the jni at first, but then i get an error message for several files that are missing on \android\obj\local\armeabi (e.g: libar2.a , libkpm.a, libutil.a)

how can i compile & run the project?
(i havn't made any changes yet, but i will, later on)

thanks!

**Comment by ThorstenBux** [comment]
Hi @tzaccai ,

please follow the instructions here: http://artoolkit.org/documentation/doku.php?id=4_Android:android_native

and tell me if that worked for you.

Best
Thorsten

**Comment by ThorstenBux** [comment]
Closing as resolved due to no response. Please feel free to ping this issue again if you still have trouble.
