### ISSUE TITLE
UnsatisfiedLinkErro  couldn't find "libc++_shared.so

### ISSUE THREAD

**Issue by joginder89** [artoolkit/artoolkit5#219]
Hi, When I try to run the `nftSimpleProj` I get this error. 

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.artoolkit.ar.samples.NftSimple-1/base.apk"],nativeLibraryDirectories=[/data/app/org.artoolkit.ar.samples.NftSimple-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libc++_shared.so"
                                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                                      at java.lang.System.loadLibrary(System.java:1076)
                                                                                      at org.artoolkit.ar.samples.nftSimple.nftSimpleActivity.<clinit>(nftSimpleActivity.java:87)
                                                                                      at java.lang.Class.newInstance(Native Method)
                                                                                      at android.app.Instrumentation.newActivity(Instrumentation.java:1090)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
`

**Comment by ThorstenBux** [comment]
Please read the documentation here and follow it closely.

You need to install Android NDK and run the build.sh from within the android directory.

**Comment by StancuFlorin** [comment]
I didn't found where is this written
"You need to install Android NDK and run the build.sh from within the android directory."

Can you share a link?

Thanks,
Florin.

**Comment by ThorstenBux** [comment]
My bad, I forgot to paste the link:

http://artoolkit.org/documentation/doku.php?id=4_Android:android_native

Cheers

**Comment by prikou** [comment]
@ThorstenBux  hi i am not able to access the link that you have provided above... is there anyway that ou can help me with this ?

regards,
Prikou

**Comment by ThorstenBux** [comment]
https://archive.artoolkit.org/documentation/doku.php?id=4_Android:android_native

**Comment by prikou** [comment]
@ThorstenBux  thanx 💯
