### ISSUE TITLE
Support for other devices besides BT-200?

### ISSUE THREAD

**Issue by skylook** [artoolkit/artoolkit5#99]
Is there other devices that supported besides BT-200? 
Like ODG R-7 or others?

**Comment by philip-lamb** [comment]
Until we have access to a particular piece of hardware, it's difficult to add support. We welcome contributions of course, both of hardware and supporting code.

**Comment by skylook** [comment]
Yeah, more and more AR glasses will come like Hololens, Atheer One, ODG R-7 and BT-300. A good choice may be building an easy Android tool for stereo camera and optical see-thru display calibration.

Also a platform user can contribute calibration results is helpful.

**Comment by jf-mgd** [comment]
Hi,

I have a BT300 prototype lent by Epson. I would like to know if someone can give me a hint about the "registration" procedure for this kind of device.
I read the Using an Optical See-Through Display](http://artoolkit.org/documentation/doku.php?id=8_Advanced_Topics:config_optical_see-through) page, but have many problems:
* Moverio did not come with Google Play, so I cannot install the android calibration application (I can install an APK manually, but didn't find it on artoolkit official website)
* Even if I could run the calibration application, the "normal usage" I would see for those device is "offline". Is there a link where I could download manually the calibration data (to embed it in the final application APK)? Found that the camera params database is on this server "https://omega.artoolworks.com/app/calib_camera", but I do not see how to download calibration data for a particular camera / device.
* When running "calib_optical" on Moverio, I have an error indicating that curl library is not found:
`12-19 15:57:17.353 4414-4414/? E/art: dlopen("/data/app/org.artoolkit.ar.samples.CalibOptical-2/lib/x86/libcalib_optical_Native.so", RTLD_LAZY) failed: dlopen failed: library "libcurl.so" not found
12-19 15:57:17.354 4414-4414/? D/AndroidRuntime: Shutting down VM
12-19 15:57:17.355 4414-4414/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.artoolkit.ar.samples.CalibOptical, PID: 4414
                                                 java.lang.UnsatisfiedLinkError: dlopen failed: library "libcurl.so" not found
                                                     at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                     at java.lang.System.loadLibrary(System.java:988)
                                                     at org.artoolkit.ar.utils.calib_optical.calib_optical_Activity.<clinit>(calib_optical_Activity.java:77)
                                                     at java.lang.reflect.Constructor.newInstance(Native Method)
                                                     at java.lang.Class.newInstance(Class.java:1603)
                                                     at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2226)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5258)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
12-19 15:57:17.359 3026-3352/? D/ufoEGL: Surface destroy: ANDROID_NATIVE_WINDOW_MAGIC`
I Have no access to a bt200 device, but I wonder if the libcurl was on those device (I tried on a Galaxy S7 and the app runs), or if the "calibration tool" was changed since bt200 related data was generated by artoolkit team... This problem let me think that even with camera calibration APK, i could have problem to run the app...
* Does the person whose generated bt200 related data remainds what was the procedure he applied?

**Comment by jf-mgd** [comment]
Managed to run "calib_optical" on bt300, copying manually "libcrypto.so" / "libcurl.so" / "libssl.so" from "ARToolKit5-bin-5.3.2-Android\EclipseProjects\ARMulti\libs\x86" to "ARToolKit5-bin-5.3.2-Android\AndroidStudioProjects\calib_opticalProj\calib_optical\src\main\jniLibs\x86", rebuilt APK, _et voilà_.
But the other questions I had still remains...

**Comment by BigBlueCeiling** [comment]
@jf-mgd  I'm curious how you progressed. I'm looking at options for the BT-300 right now since official support isn't there yet on other platforms and ARToolkit is at least hackable.

Also: @philip-lamb - does the NZ ARToolkit team have access to a BT-300?

**Comment by ThorstenBux** [comment]
Hi, we are in the stage to get access to some devices. As of now, unfortunately, we don't have access to a BT-300. We would highly appreciate any community support on that.

**Comment by nicomgd** [comment]
@ThorstenBux @BigBlueCeiling Hi, I worked with @jf-mgd on this, we never quite managed to get the proper calibration running (lack of time) so we use a wide sets of workarounds to have something running. We still, for now, have the hardware at hand, so let us know if we can provide you with data - we don't have much free time for this tough... :(
